#!/bin/sh

case "$1" in
  start)
	# process user commands
	[ -f /etc/rc.local ] && {
		sh /etc/rc.local
	}
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

